### ISSUE TITLE
Importing SCSS files results in error

### ISSUE THREAD

**Issue by stevenlafl** [usds/uswds-vue#8]
Documentation says:
```
@import "~uswds/dist/scss/uswds.css";
@import "~uswds-vue/src/styles/uswds-vue.scss";
```

However, there is no such `~uswds/dist/scss/uswds.css` but there is `~uswds/dist/scss/uswds.scss` which generates errors on the font includes or `~uswds/dist/css/uswds.css` which works properly.

**Comment by jcandan** [comment]
I can vouch for this bug. 

### Problem

Documentation says to use:

```
  @import "~uswds/dist/scss/uswds.css";
```

However, that path is incorrect, and the file does not exist.

```
Module not found: Error: Can't resolve 'uswds/dist/scss/uswds.css'
```

Changing to an existing scss file, `@import "~uswds/dist/scss/uswds.scss";`, causes a `Failed to compile error`:

```
Module not found: Error: Can't resolve '../fonts/merriweather/Latin-Merriweather-Bold.ttf' in '/app/src'
```

### Proposed resolution

Update documentation to use `@import "~uswds/dist/css/uswds.css";`

### ~~Caveat~~

~~This may prevent us from overriding scss variables, like `$primary`. Is there a way to so when using `~uswds/dist/css/uswds.css`? If not, how might we tackle the error when using `@import "~uswds/dist/scss/uswds.scss";`?~~

**Comment by jcandan** [comment]
I am able to override the color following Bootstrap [docs](https://getbootstrap.com/docs/4.0/getting-started/theming/#modify-map):

```
# @file src/scss/colors.scss

$theme-colors: (
	"primary": red,
);
```

Providing the path as specified above to the `css` file, and to my new `scss` colors override:

```
<style lang="scss">
  @import "@/scss/colors.scss";
  @import "~uswds/dist/css/uswds.css";
  @import "~uswds-vue/src/styles/uswds-vue.scss";
</style>
```

**Comment by mikepif** [comment]
Sorry for delay, been swamped - I'm working on a new version, hope to have it out soon and I'll address this issue.

**Comment by thepipster** [comment]
@jcandan I gave you access, so you can now merge in any updates.
